name: ci-cd-min
on:
  workflow_call:
    inputs:
      app_type: { type: string, required: true }
      deploy_in_workflow: { type: boolean, default: true }
jobs:
  t-deploy:
    if: false
    uses: triarchsecurity/shared-workflows/.github/workflows/deploy-firebase.yml@release/v9
    with:
      firebase_project_id: x
      environment: dev
    secrets:
      FIREBASE_SA_KEY: ${{ secrets.FIREBASE_SA_KEY }}
      ADMIN_API_TOKEN: ${{ secrets.ADMIN_API_TOKEN }}
      GH_PAT: ${{ secrets.GH_PAT }}
