name: ci-cd-min
on:
  workflow_call:
    inputs:
      app_type: { type: string, required: true }
      deploy_in_workflow: { type: boolean, default: true }
jobs:
  t-deploy:
    if: false
    uses: triarchsecurity/shared-workflows/.github/workflows/deploy-firebase.yml@release/v9
    with:
      firebase_project_id: x
      environment: dev
    secrets: inherit
  t-notify:
    if: false
    uses: triarchsecurity/shared-workflows/.github/workflows/notify.yml@release/v9
    with:
      status: success
      project_name: x
    secrets: inherit
